"""change user_post ondelete rules

Revision ID: d8565927fe45
Revises: 
Create Date: 2023-07-16 15:15:16.721209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8565927fe45'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_post_post_id_fkey', 'user_post', type_='foreignkey')
    op.drop_constraint('user_post_user_id_fkey', 'user_post', type_='foreignkey')
    op.create_foreign_key(None, 'user_post', 'post', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_post', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_post', type_='foreignkey')
    op.drop_constraint(None, 'user_post', type_='foreignkey')
    op.create_foreign_key('user_post_user_id_fkey', 'user_post', 'user', ['user_id'], ['id'])
    op.create_foreign_key('user_post_post_id_fkey', 'user_post', 'post', ['post_id'], ['id'])
    # ### end Alembic commands ###
